export enum SetMultiplierType {
  Income,
  Ore,
  Research,
  FreeGems,
  OfflineProduction,
  ClickOutput,
  MerchantRevenue,
}

export type BlueprintSet = Readonly<{
  setName: string;
  multiplierType: SetMultiplierType;
  blueprints: string[];
  achievementRanks?: AchievementRank[]; // TODO: fill in score boundaries for other sets
}>;

type AchievementRank = Readonly<{
  scoreBoundary: number;
  totalMultiplier: number;
}>;

export const BLUEPRINT_SETS: BlueprintSet[] = [
  {
    setName: 'Wood',
    multiplierType: SetMultiplierType.Income,
    blueprints: ['Wood', 'Club', 'Arrows', 'Bow', 'Copper Axe', 'Bronze Spear'],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 96, totalMultiplier: 1.2 },
      { scoreBoundary: 180, totalMultiplier: 1.4 },
      { scoreBoundary: 435, totalMultiplier: 1.6 },
      { scoreBoundary: 750, totalMultiplier: 1.8 },
      { scoreBoundary: 1470, totalMultiplier: 2.0 },
      { scoreBoundary: 2100, totalMultiplier: 2.2 },
      { scoreBoundary: 4350, totalMultiplier: 2.4 },
      { scoreBoundary: 7500, totalMultiplier: 2.6 },
      { scoreBoundary: 14700, totalMultiplier: 2.8 },
      { scoreBoundary: 21000, totalMultiplier: 3.0 },
      { scoreBoundary: 43500, totalMultiplier: 3.2 },
      { scoreBoundary: 75000, totalMultiplier: 3.4 },
      { scoreBoundary: 147000, totalMultiplier: 3.6 },
      { scoreBoundary: 210000, totalMultiplier: 3.8 },
      { scoreBoundary: 435000, totalMultiplier: 4.0 },
      { scoreBoundary: 750000, totalMultiplier: 4.2 },
      { scoreBoundary: 1.5e6, totalMultiplier: 4.4 },
      { scoreBoundary: 2.1e6, totalMultiplier: 4.6 },
      { scoreBoundary: 4.4e6, totalMultiplier: 4.8 },
      { scoreBoundary: 7.5e6, totalMultiplier: 5.0 },
      { scoreBoundary: 1.27e7, totalMultiplier: 5.2 },
      { scoreBoundary: 2.02e7, totalMultiplier: 5.4 },
      { scoreBoundary: 2.77e7, totalMultiplier: 5.6 },
      { scoreBoundary: 3.52e7, totalMultiplier: 5.8 },
      { scoreBoundary: 4.27e7, totalMultiplier: 6.0 },
    ],
  },
  {
    setName: 'Leather',
    multiplierType: SetMultiplierType.Income,
    blueprints: ['Rawhide', 'Leather', 'Boots', 'Hilt', 'Leather Armor', 'Imp. Leather Armor'],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 96, totalMultiplier: 1.2 },
      { scoreBoundary: 180, totalMultiplier: 1.4 },
      { scoreBoundary: 435, totalMultiplier: 1.6 },
      { scoreBoundary: 750, totalMultiplier: 1.8 },
      { scoreBoundary: 1470, totalMultiplier: 2.0 },
      { scoreBoundary: 2100, totalMultiplier: 2.2 },
      { scoreBoundary: 4350, totalMultiplier: 2.4 },
      { scoreBoundary: 7500, totalMultiplier: 2.6 },
      { scoreBoundary: 14700, totalMultiplier: 2.8 },
      { scoreBoundary: 21000, totalMultiplier: 3.0 },
      { scoreBoundary: 43500, totalMultiplier: 3.2 },
      { scoreBoundary: 75000, totalMultiplier: 3.4 },
      { scoreBoundary: 147000, totalMultiplier: 3.6 },
      { scoreBoundary: 210000, totalMultiplier: 3.8 },
      { scoreBoundary: 435000, totalMultiplier: 4.0 },
      { scoreBoundary: 750000, totalMultiplier: 4.2 },
      { scoreBoundary: 1.5e6, totalMultiplier: 4.4 },
      { scoreBoundary: 2.1e6, totalMultiplier: 4.6 },
      { scoreBoundary: 4.4e6, totalMultiplier: 4.8 },
      { scoreBoundary: 7.5e6, totalMultiplier: 5.0 },
      { scoreBoundary: 1.27e7, totalMultiplier: 5.2 },
      { scoreBoundary: 2.02e7, totalMultiplier: 5.4 },
      { scoreBoundary: 2.77e7, totalMultiplier: 5.6 },
      { scoreBoundary: 3.52e7, totalMultiplier: 5.8 },
      { scoreBoundary: 4.27e7, totalMultiplier: 6.0 },
    ],
  },
  {
    setName: 'Copper',
    multiplierType: SetMultiplierType.Income,
    blueprints: ['Copper Ore', 'Copper Ingots', 'Copper Axe', 'Copper Blades', 'Copper Knife', 'Copper Dagger'],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 96, totalMultiplier: 1.2 },
      { scoreBoundary: 180, totalMultiplier: 1.4 },
      { scoreBoundary: 435, totalMultiplier: 1.6 },
      { scoreBoundary: 750, totalMultiplier: 1.8 },
      { scoreBoundary: 1470, totalMultiplier: 2.0 },
      { scoreBoundary: 2100, totalMultiplier: 2.2 },
      { scoreBoundary: 4350, totalMultiplier: 2.4 },
      { scoreBoundary: 7500, totalMultiplier: 2.6 },
      { scoreBoundary: 14700, totalMultiplier: 2.8 },
      { scoreBoundary: 21000, totalMultiplier: 3.0 },
      { scoreBoundary: 43500, totalMultiplier: 3.2 },
      { scoreBoundary: 75000, totalMultiplier: 3.4 },
      { scoreBoundary: 147000, totalMultiplier: 3.6 },
      { scoreBoundary: 210000, totalMultiplier: 3.8 },
      { scoreBoundary: 435000, totalMultiplier: 4.0 },
      { scoreBoundary: 750000, totalMultiplier: 4.2 },
      { scoreBoundary: 1.5e6, totalMultiplier: 4.4 },
      { scoreBoundary: 2.1e6, totalMultiplier: 4.6 },
      { scoreBoundary: 4.4e6, totalMultiplier: 4.8 },
      { scoreBoundary: 7.5e6, totalMultiplier: 5.0 },
      { scoreBoundary: 1.27e7, totalMultiplier: 5.2 },
      { scoreBoundary: 2.02e7, totalMultiplier: 5.4 },
      { scoreBoundary: 2.77e7, totalMultiplier: 5.6 },
      { scoreBoundary: 3.52e7, totalMultiplier: 5.8 },
      { scoreBoundary: 4.27e7, totalMultiplier: 6.0 },
    ],
  },
  {
    setName: 'Bronze',
    multiplierType: SetMultiplierType.Income,
    blueprints: [
      'Tin Ore',
      'Bronze Ingots',
      'Bronze Spear',
      'Bronze Shield',
      'Bronze Blades',
      'Bronze Dagger',
      'Bronze Sword',
    ],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 112, totalMultiplier: 1.2 },
      { scoreBoundary: 210, totalMultiplier: 1.4 },
      { scoreBoundary: 508, totalMultiplier: 1.6 },
      { scoreBoundary: 875, totalMultiplier: 1.8 },
      { scoreBoundary: 1715, totalMultiplier: 2.0 },
      { scoreBoundary: 2450, totalMultiplier: 2.2 },
      { scoreBoundary: 5075, totalMultiplier: 2.4 },
      { scoreBoundary: 8750, totalMultiplier: 2.6 },
      { scoreBoundary: 17150, totalMultiplier: 2.8 },
      { scoreBoundary: 24500, totalMultiplier: 3.0 },
      { scoreBoundary: 50750, totalMultiplier: 3.2 },
      { scoreBoundary: 87500, totalMultiplier: 3.4 },
      { scoreBoundary: 171500, totalMultiplier: 3.6 },
      { scoreBoundary: 245000, totalMultiplier: 3.8 },
      { scoreBoundary: 507500, totalMultiplier: 4.0 },
      { scoreBoundary: 875000, totalMultiplier: 4.2 },
      { scoreBoundary: 1.7e6, totalMultiplier: 4.4 },
      { scoreBoundary: 2.5e6, totalMultiplier: 4.6 },
      { scoreBoundary: 5.1e6, totalMultiplier: 4.8 },
      { scoreBoundary: 8.8e6, totalMultiplier: 5.0 },
      { scoreBoundary: 1.49e7, totalMultiplier: 5.2 },
      { scoreBoundary: 2.36e7, totalMultiplier: 5.4 },
      { scoreBoundary: 3.24e7, totalMultiplier: 5.6 },
      { scoreBoundary: 4.11e7, totalMultiplier: 5.8 },
      { scoreBoundary: 4.99e7, totalMultiplier: 6.0 },
    ],
  },
  {
    setName: 'Iron',
    multiplierType: SetMultiplierType.Income,
    blueprints: [
      'Coal',
      'Iron Ore',
      'Iron Ingots',
      'Iron Mace',
      'Iron Rivets',
      'Iron Helmet',
      'Iron Plates',
      'Imp. Leather Armor',
      'Iron Blades',
      'Iron Sword',
      'Iron Armor',
      'Iron Claymore',
    ],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 192, totalMultiplier: 1.2 },
      { scoreBoundary: 360, totalMultiplier: 1.4 },
      { scoreBoundary: 870, totalMultiplier: 1.6 },
      { scoreBoundary: 1500, totalMultiplier: 1.8 },
      { scoreBoundary: 2940, totalMultiplier: 2.0 },
      { scoreBoundary: 4200, totalMultiplier: 2.2 },
      { scoreBoundary: 8700, totalMultiplier: 2.4 },
      { scoreBoundary: 15000, totalMultiplier: 2.6 },
      { scoreBoundary: 29400, totalMultiplier: 2.8 },
      { scoreBoundary: 42000, totalMultiplier: 3.0 },
      { scoreBoundary: 87000, totalMultiplier: 3.2 },
      { scoreBoundary: 150000, totalMultiplier: 3.4 },
      { scoreBoundary: 294000, totalMultiplier: 3.6 },
      { scoreBoundary: 420000, totalMultiplier: 3.8 },
      { scoreBoundary: 870000, totalMultiplier: 4.0 },
      { scoreBoundary: 1500000, totalMultiplier: 4.2 },
      { scoreBoundary: 2.9e6, totalMultiplier: 4.4 },
      { scoreBoundary: 4.2e6, totalMultiplier: 4.6 },
      { scoreBoundary: 8.7e6, totalMultiplier: 4.8 },
      { scoreBoundary: 1.5e7, totalMultiplier: 5.0 },
      { scoreBoundary: 2.55e7, totalMultiplier: 5.2 },
      { scoreBoundary: 4.05e7, totalMultiplier: 5.4 },
      { scoreBoundary: 5.55e7, totalMultiplier: 5.6 },
      { scoreBoundary: 7.05e7, totalMultiplier: 5.8 },
      { scoreBoundary: 8.55e7, totalMultiplier: 6.0 },
    ],
  },
  {
    setName: 'Precious',
    multiplierType: SetMultiplierType.Income,
    blueprints: [
      'Gold Ore',
      'Gold Ingots',
      'Gold Ring',
      'Gold Necklace',
      'Steel',
      'Steel Blades',
      'Katana',
      'Magnificent Hilt',
      'Magnificent Sword',
      'Magnificent Armor',
    ],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 160, totalMultiplier: 1.2 },
      { scoreBoundary: 300, totalMultiplier: 1.4 },
      { scoreBoundary: 725, totalMultiplier: 1.6 },
      { scoreBoundary: 1250, totalMultiplier: 1.8 },
      { scoreBoundary: 2450, totalMultiplier: 2.0 },
      { scoreBoundary: 3500, totalMultiplier: 2.2 },
      { scoreBoundary: 7250, totalMultiplier: 2.4 },
      { scoreBoundary: 12500, totalMultiplier: 2.6 },
      { scoreBoundary: 24500, totalMultiplier: 2.8 },
      { scoreBoundary: 35000, totalMultiplier: 3.0 },
      { scoreBoundary: 72500, totalMultiplier: 3.2 },
      { scoreBoundary: 125000, totalMultiplier: 3.4 },
      { scoreBoundary: 245000, totalMultiplier: 3.6 },
      { scoreBoundary: 350000, totalMultiplier: 3.8 },
      { scoreBoundary: 725000, totalMultiplier: 4.0 },
      { scoreBoundary: 1300000, totalMultiplier: 4.2 },
      { scoreBoundary: 2.5e6, totalMultiplier: 4.4 },
      { scoreBoundary: 3.5e6, totalMultiplier: 4.6 },
      { scoreBoundary: 7.3e6, totalMultiplier: 4.8 },
      { scoreBoundary: 1.25e7, totalMultiplier: 5.0 },
      { scoreBoundary: 2.12e7, totalMultiplier: 5.2 },
      { scoreBoundary: 3.37e7, totalMultiplier: 5.4 },
      { scoreBoundary: 4.62e7, totalMultiplier: 5.6 },
      { scoreBoundary: 5.87e7, totalMultiplier: 5.8 },
      { scoreBoundary: 7.12e7, totalMultiplier: 6.0 },
    ],
  },
  {
    setName: 'Renaissance',
    multiplierType: SetMultiplierType.Income,
    blueprints: [
      'Mechanical Parts',
      'Magnificent Crossbow',
      'Sulfur',
      'Halberd',
      'Compass',
      'Saltpeter',
      'Gunpowder',
      'Weapon Parts',
      'Pistol',
      'Musket',
    ],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 100, totalMultiplier: 1.5 },
      { scoreBoundary: 300, totalMultiplier: 2.0 },
      { scoreBoundary: 1200, totalMultiplier: 2.5 },
      { scoreBoundary: 2000, totalMultiplier: 3.0 },
      { scoreBoundary: 4000, totalMultiplier: 3.5 },
      { scoreBoundary: 8000, totalMultiplier: 4.0 },
      { scoreBoundary: 20000, totalMultiplier: 4.5 },
      { scoreBoundary: 40000, totalMultiplier: 5.0 },
      { scoreBoundary: 60000, totalMultiplier: 5.5 },
      { scoreBoundary: 100000, totalMultiplier: 6.0 },
      { scoreBoundary: 200000, totalMultiplier: 6.5 },
      { scoreBoundary: 400000, totalMultiplier: 7.0 },
      { scoreBoundary: 600000, totalMultiplier: 7.5 },
      { scoreBoundary: 1000000, totalMultiplier: 8.0 },
      { scoreBoundary: 3000000, totalMultiplier: 8.5 },
      { scoreBoundary: 5000000, totalMultiplier: 9.0 },
      { scoreBoundary: 8.0e6, totalMultiplier: 9.5 },
      { scoreBoundary: 1.5e7, totalMultiplier: 10.0 },
      { scoreBoundary: 3.0e7, totalMultiplier: 10.5 },
      { scoreBoundary: 5.0e7, totalMultiplier: 11.0 },
      { scoreBoundary: 8.0e7, totalMultiplier: 11.5 },
      { scoreBoundary: 1.5e8, totalMultiplier: 12.0 },
      { scoreBoundary: 3.0e8, totalMultiplier: 12.5 },
      { scoreBoundary: 5.0e8, totalMultiplier: 13.0 },
      { scoreBoundary: 1.5e9, totalMultiplier: 14.0 },
      { scoreBoundary: 1.0e10, totalMultiplier: 15.0 },
      { scoreBoundary: 1.0e11, totalMultiplier: 16.0 },
      { scoreBoundary: 1.0e12, totalMultiplier: 17.0 },
      { scoreBoundary: 1.0e13, totalMultiplier: 18.0 },
      { scoreBoundary: 1.0e14, totalMultiplier: 19.0 },
    ],
  },
  {
    setName: 'Industrial',
    multiplierType: SetMultiplierType.Income,
    blueprints: [
      'Microscope',
      'Clockwork',
      'Clock',
      'Electro Magnet',
      'Machine Parts',
      'Camera',
      'Electrical Parts',
      'Motor Unit',
      'Steam Engine',
      'Telephone',
      'Steam Boat',
      'Locomotive',
    ],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 100, totalMultiplier: 1.5 },
      { scoreBoundary: 300, totalMultiplier: 2.0 },
      { scoreBoundary: 1200, totalMultiplier: 2.5 },
      { scoreBoundary: 2000, totalMultiplier: 3.0 },
      { scoreBoundary: 4000, totalMultiplier: 3.5 },
      { scoreBoundary: 8000, totalMultiplier: 4.0 },
      { scoreBoundary: 20000, totalMultiplier: 4.5 },
      { scoreBoundary: 40000, totalMultiplier: 5.0 },
      { scoreBoundary: 60000, totalMultiplier: 5.5 },
      { scoreBoundary: 100000, totalMultiplier: 6.0 },
      { scoreBoundary: 200000, totalMultiplier: 6.5 },
      { scoreBoundary: 400000, totalMultiplier: 7.0 },
      { scoreBoundary: 600000, totalMultiplier: 7.5 },
      { scoreBoundary: 1000000, totalMultiplier: 8.0 },
      { scoreBoundary: 3000000, totalMultiplier: 8.5 },
      { scoreBoundary: 5000000, totalMultiplier: 9.0 },
      { scoreBoundary: 8.0e6, totalMultiplier: 9.5 },
      { scoreBoundary: 1.5e7, totalMultiplier: 10.0 },
      { scoreBoundary: 3.0e7, totalMultiplier: 10.5 },
      { scoreBoundary: 5.0e7, totalMultiplier: 11.0 },
      { scoreBoundary: 8.0e7, totalMultiplier: 11.5 },
      { scoreBoundary: 1.5e8, totalMultiplier: 12.0 },
      { scoreBoundary: 3.0e8, totalMultiplier: 12.5 },
      { scoreBoundary: 5.0e8, totalMultiplier: 13.0 },
      { scoreBoundary: 1.5e9, totalMultiplier: 14.0 },
    ],
  },
  {
    setName: 'Mining Tools',
    multiplierType: SetMultiplierType.Ore,
    blueprints: ['Shovel', 'Lump Hammer', 'Pickaxe', 'Gunpowder'],
  },
  {
    setName: 'Science Tools',
    multiplierType: SetMultiplierType.Research,
    blueprints: ['Sickle', 'Chisel', 'Mechanical Parts', 'Compass'],
  },
  {
    setName: 'Exploration',
    multiplierType: SetMultiplierType.Research,
    blueprints: ['Paper', 'Paper Sheets', 'Map', 'Book', 'Rowboat', 'Spyglass', 'Compass'],
  },
  {
    setName: 'Modern Exploration',
    multiplierType: SetMultiplierType.Research,
    blueprints: ['Entrenching Tool', 'Tent', 'Backpack', 'Diving Gear', 'Electric Motor', 'Submarine'],
  },
  {
    setName: 'Cut Gems',
    multiplierType: SetMultiplierType.FreeGems,
    blueprints: ['Cut Emerald', 'Cut Ruby', 'Cut Sapphire', 'Cut Onyx'],
  },
  {
    setName: 'Emerald',
    multiplierType: SetMultiplierType.OfflineProduction,
    blueprints: ['Uncut Emerald', 'Cut Emerald', 'Emerald Ring'],
  },
  {
    setName: 'Ruby',
    multiplierType: SetMultiplierType.OfflineProduction,
    blueprints: ['Uncut Ruby', 'Cut Ruby', 'Ruby Ring'],
  },
  {
    setName: 'Sapphire',
    multiplierType: SetMultiplierType.OfflineProduction,
    blueprints: ['Uncut Sapphire', 'Cut Sapphire', 'Sapphire Ring'],
  },
  {
    setName: 'Onyx',
    multiplierType: SetMultiplierType.OfflineProduction,
    blueprints: ['Uncut Onyx', 'Cut Onyx', 'Onyx Ring'],
  },
  {
    setName: 'Hammer',
    multiplierType: SetMultiplierType.ClickOutput,
    blueprints: ['Lump Hammer', 'War Hammer', 'Magnificent Hammer'],
  },
  {
    setName: 'Knife',
    multiplierType: SetMultiplierType.MerchantRevenue,
    blueprints: ['Sickle', 'Magnificent Dagger'],
  },
  {
    setName: 'Modern Weapons',
    multiplierType: SetMultiplierType.MerchantRevenue,
    blueprints: [
      'Magnificent Bow',
      'Mortar',
      'Caplock Pistol',
      'Derringer',
      'Rocket Launcher',
      'Lever Action Rifle',
      'Cannon',
      'Revolver',
      'Bolt Action Rifle',
    ],
  },
  {
    setName: 'Music Instruments',
    multiplierType: SetMultiplierType.MerchantRevenue,
    blueprints: ['Flute', 'Bongos', 'Harp', 'Tambourine', 'Trumpet', 'Viola', 'Harpsichord', 'Snare Drum', 'Saxophone'],
  },
  {
    setName: 'Vehicles',
    multiplierType: SetMultiplierType.Income,
    blueprints: ['Bicycle', 'Glider', 'Combustion Engine', 'Motorcycle', 'Car', 'Truck', 'Airplane'],
    achievementRanks: [
      { scoreBoundary: 0, totalMultiplier: 1 },
      { scoreBoundary: 100, totalMultiplier: 1.5 },
      { scoreBoundary: 300, totalMultiplier: 2.0 },
      { scoreBoundary: 1200, totalMultiplier: 2.5 },
      { scoreBoundary: 2000, totalMultiplier: 3.0 },
      { scoreBoundary: 4000, totalMultiplier: 3.5 },
      { scoreBoundary: 8000, totalMultiplier: 4.0 },
      { scoreBoundary: 20000, totalMultiplier: 4.5 },
      { scoreBoundary: 40000, totalMultiplier: 5.0 },
      { scoreBoundary: 60000, totalMultiplier: 5.5 },
      { scoreBoundary: 100000, totalMultiplier: 6.0 },
      { scoreBoundary: 200000, totalMultiplier: 6.5 },
      { scoreBoundary: 400000, totalMultiplier: 7.0 },
      { scoreBoundary: 600000, totalMultiplier: 7.5 },
      { scoreBoundary: 1000000, totalMultiplier: 8.0 },
      { scoreBoundary: 3000000, totalMultiplier: 8.5 },
      { scoreBoundary: 5000000, totalMultiplier: 9.0 },
      { scoreBoundary: 8.0e6, totalMultiplier: 9.5 },
      { scoreBoundary: 1.5e7, totalMultiplier: 10.0 },
      { scoreBoundary: 3.0e7, totalMultiplier: 10.5 },
      { scoreBoundary: 5.0e7, totalMultiplier: 11.0 },
      { scoreBoundary: 8.0e7, totalMultiplier: 11.5 },
      { scoreBoundary: 1.5e8, totalMultiplier: 12.0 },
      { scoreBoundary: 3.0e8, totalMultiplier: 12.5 },
      { scoreBoundary: 5.0e8, totalMultiplier: 13.0 },
      { scoreBoundary: 1.5e9, totalMultiplier: 14.0 },
      { scoreBoundary: 1.0e10, totalMultiplier: 15.0 },
      { scoreBoundary: 1.0e11, totalMultiplier: 16.0 },
      { scoreBoundary: 1.0e12, totalMultiplier: 17.0 },
      { scoreBoundary: 1.0e13, totalMultiplier: 18.0 },
      { scoreBoundary: 1.0e14, totalMultiplier: 19.0 },
    ],
  },
];
