export const BLUEPRINT_UPGRADE_COSTS = new Map<string, number>([
  ['Wood', 11],
  ['Club', 11],
  ['Arrows', 12],
  ['Bow', 13],
  ['Rawhide', 14],
  ['Leather', 15],
  ['Boots', 16],
  ['Hilt', 16],
  ['Leather Armor', 17],
  ['Copper Ore', 18],
  ['Copper Ingots', 19],
  ['Copper Axe', 20],
  ['Copper Blades', 20],
  ['Copper Knife', 21],
  ['Copper Dagger', 22],
  ['Tin Ore', 23],
  ['Bronze Ingots', 24],
  ['Bronze Spear', 24],
  ['Bronze Shield', 25],
  ['Bronze Blades', 26],
  ['Bronze Dagger', 27],
  ['Bronze Sword', 28],
  ['Sickle', 28],
  ['Coal', 29],
  ['Iron Ore', 30],
  ['Iron Ingots', 31],
  ['Chisel', 31],
  ['Iron Mace', 31],
  ['Iron Rivets', 32],
  ['Shovel', 32],
  ['Lump Hammer', 33],
  ['Iron Helmet', 33],
  ['Iron Plates', 34],
  ['Imp. Leather Armor', 35],
  ['Iron Blades', 37],
  ['Iron Sword', 38],
  ['Iron Armor', 39],
  ['Iron Claymore', 41],
  ['Paper', 41],
  ['Gold Ore', 42],
  ['Gold Ingots', 45],
  ['Uncut Emerald', 47],
  ['Gold Ring', 48],
  ['Cut Emerald', 50],
  ['Gold Necklace', 53],
  ['Emerald Ring', 54],
  ['Uncut Ruby', 55],
  ['Paper Sheets', 55],
  ['Steel', 56],
  ['Pickaxe', 57],
  ['War Hammer', 58],
  // ["Entrenching Tool", TODO],
  ['Steel Blades', 60],
  ['Cut Ruby', 61],
  ['Map', 62],
  ['Ruby Ring', 63],
  ['Book', 64],
  // ["Tent", TODO],
  ['Katana', 66],
  ['Magnificent Bow', 68],
  // ["Backpack", TODO],
  ['Magnificent Hilt', 71],
  ['Magnificent Hammer', 73],
  ['Magnificent Dagger', 74],
  ['Magnificent Sword', 77],
  ['Rowboat', 78],
  ['Uncut Sapphire', 79],
  ['Magnificent Armor', 83],
  ['Flute', 83],
  ['Mechanical Parts', 84],
  ['Spyglass', 85],
  ['Magnificent Crossbow', 86],
  ['Sulfur', 86],
  ['Bongos', 87],
  ['Cut Sapphire', 87],
  ['Halberd', 88],
  ['Microscope', 89],
  ['Compass', 90],
  ['Clockwork', 91],
  ['Harp', 91],
  ['Saltpeter', 92],
  ['Tambourine', 93],
  ['Trumpet', 94],
  ['Sapphire Ring', 95],
  ['Clock', 96],
  ['Viola', 97],
  ['Gunpowder', 98],
  ['Uncut Onyx', 100],
  ['Harpsichord', 101],
  ['Weapon Parts', 103],
  ['Snare Drum', 104],
  ['Cut Onyx', 106],
  ['Saxophone', 106],
  ['Electro Magnet', 107],
  ['Pistol', 108],
  ['Bicycle', 108],
  ['Machine Parts', 109],
  ['Camera', 110],
  ['Onyx Ring', 110],
  ['Mortar', 112],
  ['Electrical Parts', 113],
  ['Musket', 114],
  ['Motor Unit', 116],
  ['Glider', 116],
  ['Caplock Pistol', 117],
  // ["Light Bulb", TODO],
  ['Steam Engine', 118],
  ['Derringer', 118],
  // ["Lamp", TODO],
  ['Rocket Launcher', 119],
  ['Telephone', 119],
  ['Lever Action Rifle', 120],
  ['Steam Boat', 120],
  ['Cannon', 120],
  ['Locomotive', 120],
  ['Revolver', 121],
  ['Bolt Action Rifle', 122],
  // ["Diving Gear", TODO],
  ['Combustion Engine', 123],
  ['Motorcycle', 124],
  // ["Antenna", TODO],
  ['Car', 124],
  ['Truck', 125],
  // ["Flashlight", TODO],
  ['Airplane', 126],
  ['Electric Motor', 126],
  ['Submarine', 127],
  // ["Space Probe", TODO],
  // ["Rocket", TODO],
]);
