import { Blueprint } from '../types/Blueprint';

export const DEFAULT_BLUEPRINT: Blueprint = {
  productName: 'productName',
  evolutionStage: 1,
  upgradeLevel: 1,
  score: 10,
};

export const TOP_STAGE_1: Blueprint = {
  ...DEFAULT_BLUEPRINT,
  upgradeLevel: 51,
  score: 60,
};

export const DEFAULT_STAGE_2: Blueprint = {
  ...DEFAULT_BLUEPRINT,
  evolutionStage: 2,
  upgradeLevel: 1,
  score: 120,
};

export const BLUEPRINT_LIBRARY: Blueprint[] = [
  { ...DEFAULT_STAGE_2, productName: 'Wood' },
  { ...DEFAULT_BLUEPRINT, productName: 'Wood' },
  { ...DEFAULT_BLUEPRINT, productName: 'Wood' },
  { ...DEFAULT_BLUEPRINT, productName: 'Club' },
  { ...DEFAULT_BLUEPRINT, productName: 'Club' },
  { ...DEFAULT_BLUEPRINT, productName: 'Club' },
  { ...DEFAULT_BLUEPRINT, productName: 'Club' },
  { ...DEFAULT_BLUEPRINT, productName: 'Arrows' },
  { ...DEFAULT_BLUEPRINT, productName: 'Arrows' },
  { ...DEFAULT_BLUEPRINT, productName: 'Arrows' },
  { ...DEFAULT_BLUEPRINT, productName: 'Arrows' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bow' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bow' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bow' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bow' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bow' },
  { ...TOP_STAGE_1, productName: 'Bronze Spear' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bronze Spear' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bronze Spear' },
  { ...DEFAULT_STAGE_2, productName: 'Rawhide' },
  { ...DEFAULT_BLUEPRINT, productName: 'Rawhide' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather' },
  { ...DEFAULT_BLUEPRINT, productName: 'Boots' },
  { ...DEFAULT_BLUEPRINT, productName: 'Boots' },
  { ...DEFAULT_BLUEPRINT, productName: 'Boots' },
  { ...DEFAULT_BLUEPRINT, productName: 'Hilt' },
  { ...DEFAULT_BLUEPRINT, productName: 'Hilt' },
  { ...DEFAULT_BLUEPRINT, productName: 'Hilt' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Leather Armor' },
  { ...DEFAULT_STAGE_2, productName: 'Copper Ore' },
  { ...DEFAULT_STAGE_2, productName: 'Copper Ingots' },
  { ...TOP_STAGE_1, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Axe' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Blades' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Knife' },
  { ...DEFAULT_BLUEPRINT, productName: 'Copper Dagger' },
  { ...TOP_STAGE_1, productName: 'Tin Ore' },
  { ...DEFAULT_BLUEPRINT, productName: 'Tin Ore', upgradeLevel: 41, score: 50 },
  { ...TOP_STAGE_1, productName: 'Bronze Ingots' },
  { ...TOP_STAGE_1, productName: 'Bronze Spear' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bronze Shield' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bronze Blades' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bronze Dagger' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bronze Sword' },
  { ...DEFAULT_STAGE_2, productName: 'Coal' },
  { ...DEFAULT_STAGE_2, productName: 'Iron Ore' },
  { ...TOP_STAGE_1, productName: 'Iron Ingots' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Mace' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Rivets' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Helmet' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Plates' },
  { ...TOP_STAGE_1, productName: 'Imp. Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Imp. Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Imp. Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Imp. Leather Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Blades' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Sword' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Iron Claymore' },
  { ...DEFAULT_STAGE_2, productName: 'Gold Ore' },
  { ...DEFAULT_STAGE_2, productName: 'Gold Ingots' },
  { ...DEFAULT_BLUEPRINT, productName: 'Uncut Emerald' },
  { ...DEFAULT_BLUEPRINT, productName: 'Gold Ring' },
  { ...DEFAULT_BLUEPRINT, productName: 'Gold Necklace' },
  { ...DEFAULT_BLUEPRINT, productName: 'Steel' },
  { ...DEFAULT_BLUEPRINT, productName: 'Steel Blades' },
  { ...DEFAULT_BLUEPRINT, productName: 'Map' },
  { ...DEFAULT_BLUEPRINT, productName: 'Katana' },
  { ...DEFAULT_BLUEPRINT, productName: 'Magnificent Bow' },
  { ...DEFAULT_BLUEPRINT, productName: 'Magnificent Hilt' },
  { ...DEFAULT_BLUEPRINT, productName: 'Magnificent Sword' },
  { ...DEFAULT_BLUEPRINT, productName: 'Uncut Sapphire' },
  { ...DEFAULT_BLUEPRINT, productName: 'Magnificent Armor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Mechanical Parts', upgradeLevel: 21, score: 30 },
  { ...DEFAULT_BLUEPRINT, productName: 'Magnificent Crossbow' },
  { ...DEFAULT_BLUEPRINT, productName: 'Sulfur' },
  { ...DEFAULT_BLUEPRINT, productName: 'Bongos' },
  { ...DEFAULT_BLUEPRINT, productName: 'Cut Sapphire' },
  { ...DEFAULT_BLUEPRINT, productName: 'Compass' },
  { ...DEFAULT_BLUEPRINT, productName: 'Clockwork' },
  { ...DEFAULT_BLUEPRINT, productName: 'Saltpeter' },
  { ...DEFAULT_BLUEPRINT, productName: 'Gunpowder' },
  { ...DEFAULT_BLUEPRINT, productName: 'Saxophone' },
  { ...DEFAULT_BLUEPRINT, productName: 'Electro Magnet' },
  { ...DEFAULT_BLUEPRINT, productName: 'Machine Parts' },
  { ...DEFAULT_BLUEPRINT, productName: 'Camera' },
  { ...DEFAULT_BLUEPRINT, productName: 'Stethoscope' },
  { ...DEFAULT_BLUEPRINT, productName: 'Musket' },
  { ...DEFAULT_BLUEPRINT, productName: 'Motor Unit' },
  { ...DEFAULT_BLUEPRINT, productName: 'Hedge Trimmer' },
  { ...DEFAULT_BLUEPRINT, productName: 'Steam Engine' },
  { ...DEFAULT_BLUEPRINT, productName: 'Telephone' },
  { ...DEFAULT_BLUEPRINT, productName: 'Steam Boat' },
  { ...DEFAULT_BLUEPRINT, productName: 'Locomotive' },
  { ...DEFAULT_BLUEPRINT, productName: 'Tiki Torch' },
  { ...DEFAULT_BLUEPRINT, productName: 'Combustion Engine' },
  { ...DEFAULT_BLUEPRINT, productName: 'Antenna', upgradeLevel: 31, score: 40 },
  { ...DEFAULT_BLUEPRINT, productName: 'Car' },
  { ...DEFAULT_BLUEPRINT, productName: 'Truck' },
  { ...DEFAULT_BLUEPRINT, productName: 'X-Ray Machine' },
  { ...DEFAULT_BLUEPRINT, productName: 'Flashlight' },
  { ...DEFAULT_BLUEPRINT, productName: 'Movie Projector' },
  { ...DEFAULT_BLUEPRINT, productName: 'Electric Motor', upgradeLevel: 11, score: 20 },
  { ...DEFAULT_BLUEPRINT, productName: 'Monitor' },
  { ...DEFAULT_BLUEPRINT, productName: 'Lawn Mower' },
  { ...DEFAULT_BLUEPRINT, productName: 'Defibrillator' },
  { ...DEFAULT_BLUEPRINT, productName: 'Space Probe', upgradeLevel: 11, score: 20 },
  { ...DEFAULT_BLUEPRINT, productName: 'TV Set' },
  { ...DEFAULT_BLUEPRINT, productName: 'Rocket', upgradeLevel: 11, score: 20 },
  { ...DEFAULT_BLUEPRINT, productName: 'Microchip' },
  { ...DEFAULT_BLUEPRINT, productName: 'PC' },
];
